
services:
  # Service untuk aplikasi utama (Go - auth-service)
  app:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8080:8080"  # Mengekspose port container ke host
    env_file:
      - ./auth-service/.env  # File .env khusus untuk auth-service
    container_name: auth-service
    working_dir: /app/auth-service
    depends_on:
      - auth-db  # Tunggu database siap sebelum container ini jalan
    volumes:
      - ./auth-service/.env:/app/auth-service/.env
      - ./shared:/app/shared

  # Service untuk database MySQL
  # auth db ini terkait nama db di env
  auth-db:
    image: mysql:8
    container_name: mysql-auth-db
    restart: always
    env_file:
      - ./auth-service/.env  # File .env khusus untuk auth-service
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}  # Menggunakan variabel dari .env
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"  # Host 3307 → Container 3306 (MySQL default port)
    volumes:
      - db_data:/var/lib/mysql  # Menyimpan data MySQL secara persisten

  # Service untuk phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    restart: always
    environment:
      PMA_HOST: auth-db  # Host database yang akan dihubungkan (sesuai nama service db)
      PMA_PORT: 3306
    ports:
      - "8081:80"  # phpMyAdmin diakses lewat http://localhost:8081

volumes:
  db_data:  # Volume untuk menyimpan data MySQL
